name: Python application
on:
  push:
    tags:
      - 'v*'
jobs:
  PyPi:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish Python Package
      uses: mariamrf/py-package-publish-action@v1.0.0
      with:
        python_version: '3.7.0'
      env:
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}